<?

class Engine_Form_Element_Multitext extends Zend_Form_Element_Xhtml
{
    public $helper = 'formMultiText';

    protected $_isArray = true;

    public function init()
    {
        $this->addFilters(array('StringTrim'));

        if ($this->isRequired()) {
            $this->setAttrib('required', 'required');
        }
    }

    public function loadDefaultDecorators()
    {
        if ($this->loadDefaultDecoratorsIsDisabled()) {
            return;
        }

        $decorators = $this->getDecorators();
        if (empty($decorators)) {
            $this->addDecorator('ViewHelper');
            Engine_Form::addDefaultDecorators($this);
        }
    }

    public function getValue()
    {
        $v = parent::getValue(); // TODO: Change the autogenerated stub
        if (is_array($v)){
            $v = array_filter($v);
        }
        return $v;
    }

    public function setValue($value)
    {
        if (is_object($value)){
            $value = json_decode(json_encode($value, JSON_UNESCAPED_UNICODE), true);
        }
        if (is_array($value)){
            $value = array_filter($value);
        }
        return parent::setValue($value); // TODO: Change the autogenerated stub
    }
}
