<?php
class User_Plugin_RegionCodes
{
    private static $regionData = [
        array('country' => 1,
            'title' => 'Москва',
            'vkid' => -10,
            'num' => '77',
        ),
        array('country' => 1,
            'title' => 'Санкт-Петербург',
            'vkid' => -11,
            'num' => '78',
        ),
        array('country' => 1,
            'title' => 'Севастополь',
            'vkid' => -12,
            'num' => '92',
        ),
        array('country' => 1,
            'title' => 'Адыгея',
            'vkid' => 1000001,
            'num' => ' 	01',
        ),
        array('country' => 1,
            'title' => 'Алтай',
            'vkid' => 1121540,
            'num' => '04',
        ),
        array('country' => 1,
            'title' => 'Алтайский край',
            'vkid' => 1121829,
            'num' => '22',
        ),
        array('country' => 1,
            'title' => 'Амурская область',
            'vkid' => 1123488,
            'num' => '28',
        ),
        array('country' => 1,
            'title' => 'Архангельская область',
            'vkid' => 1000236,
            'num' => '29',
        ),
        array('country' => 1,
            'title' => 'Астраханская область',
            'vkid' => 1004118,
            'num' => '30',
        ),
        array('country' => 1,
            'title' => 'Башкортостан',
            'vkid' => 1004565,
            'num' => '02',
        ),
        array('country' => 1,
            'title' => 'Белгородская область',
            'vkid' => 1009404,
            'num' => '31',
        ),
        array('country' => 1,
            'title' => 'Брянская область',
            'vkid' => 1011109,
            'num' => '32',
        ),
        array('country' => 1,
            'title' => 'Бурятия',
            'vkid' => 1124157,
            'num' => '03',
        ),
        array('country' => 1,
            'title' => 'Владимирская область',
            'vkid' => 1124833,
            'num' => '33',
        ),
        array('country' => 1,
            'title' => 'Волгоградская область',
            'vkid' => 1014032,
            'num' => '34',
        ),
        array('country' => 1,
            'title' => 'Вологодская область',
            'vkid' => 1015702,
            'num' => '35',
        ),
        array('country' => 1,
            'title' => 'Воронежская область',
            'vkid' => 1023816,
            'num' => '36',
        ),
        array('country' => 1,
            'title' => 'Дагестан',
            'vkid' => 1025654,
            'num' => '05',
        ),
        array('country' => 1,
            'title' => 'Еврейская АОбл',
            'vkid' => 1127400,
            'num' => '79',
        ),
        array('country' => 1,
            'title' => 'Забайкальский край',
            'vkid' => 1159987,
            'num' => '75',
        ),
        array('country' => 1,
            'title' => 'Ивановская область',
            'vkid' => 1027297,
            'num' => '37',
        ),
        array('country' => 1,
            'title' => 'Ингушетия',
            'vkid' => 1030371,
            'num' => '06',
        ),
        array('country' => 1,
            'title' => 'Иркутская область',
            'vkid' => 1127513,
            'num' => '38',
        ),
        array('country' => 1,
            'title' => 'Кабардино-Балкарская',
            'vkid' => 1030428,
            'num' => '07',
        ),
        array('country' => 1,
            'title' => 'Калининградская область',
            'vkid' => 1030632,
            'num' => '39',
        ),
        array('country' => 1,
            'title' => 'Калмыкия',
            'vkid' => 1031793,
            'num' => '08',
        ),
        array('country' => 1,
            'title' => 'Калужская область',
            'vkid' => 1032084,
            'num' => '40',
        ),
        array('country' => 1,
            'title' => 'Камчатский край',
            'vkid' => 1128991,
            'num' => '41',
        ),
        array('country' => 1,
            'title' => 'Карачаево-Черкесская',
            'vkid' => 1035359,
            'num' => '09',
        ),
        array('country' => 1,
            'title' => 'Карелия',
            'vkid' => 1035522,
            'num' => '10',
        ),
        array('country' => 1,
            'title' => 'Кемеровская область',
            'vkid' => 1129059,
            'num' => '42',
        ),
        array('country' => 1,
            'title' => 'Кировская область',
            'vkid' => 1130218,
            'num' => '43',
        ),
        array('country' => 1,
            'title' => 'Коми',
            'vkid' => 1036606,
            'num' => '11',
        ),
        array('country' => 1,
            'title' => 'Корякский АО',
            'vkid' => 1134737,
            'num' => '41',
        ),
        array('country' => 1,
            'title' => 'Костромская область',
            'vkid' => 1037344,
            'num' => '44',
        ),
        array('country' => 1,
            'title' => 'Краснодарский край',
            'vkid' => 1040652,
            'num' => '23',
        ),
        array('country' => 1,
            'title' => 'Красноярский край',
            'vkid' => 1134771,
            'num' => '24',
        ),
        array('country' => 1,
            'title' => 'Курганская область',
            'vkid' => 1137144,
            'num' => '45',
        ),
        array('country' => 1,
            'title' => 'Курская область',
            'vkid' => 1042388,
            'num' => '46',
        ),
        array('country' => 1,
            'title' => 'Ленинградская область',
            'vkid' => 1045244,
            'num' => '47',
        ),
        array('country' => 1,
            'title' => 'Липецкая область',
            'vkid' => 1048584,
            'num' => '48',
        ),
        array('country' => 1,
            'title' => 'Магаданская область',
            'vkid' => 1138434,
            'num' => '49',
        ),
        array('country' => 1,
            'title' => 'Марий Эл',
            'vkid' => 1050307,
            'num' => '12',
        ),
        array('country' => 1,
            'title' => 'Мордовия',
            'vkid' => 1052052,
            'num' => '13',
        ),
        array('country' => 1,
            'title' => 'Московская область',
            'vkid' => 1053480,
            'num' => '50',
        ),
        array('country' => 1,
            'title' => 'Мурманская область',
            'vkid' => 1060316,
            'num' => '51',
        ),
        array('country' => 1,
            'title' => 'Ненецкий АО',
            'vkid' => 5331184,
            'num' => '83',
        ),
        array('country' => 1,
            'title' => 'Нижегородская область',
            'vkid' => 1138534,
            'num' => '52',
        ),
        array('country' => 1,
            'title' => 'Новгородская область',
            'vkid' => 1060458,
            'num' => '53',
        ),
        array('country' => 1,
            'title' => 'Новосибирская область',
            'vkid' => 1143518,
            'num' => '54',
        ),
        array('country' => 1,
            'title' => 'Омская область',
            'vkid' => 1145150,
            'num' => '55',
        ),
        array('country' => 1,
            'title' => 'Оренбургская область',
            'vkid' => 1146712,
            'num' => '56',
        ),
        array('country' => 1,
            'title' => 'Орловская область',
            'vkid' => 1064424,
            'num' => '57',
        ),
        array('country' => 1,
            'title' => 'Пензенская область',
            'vkid' => 1067455,
            'num' => '58',
        ),
        array('country' => 1,
            'title' => 'Пермский край',
            'vkid' => 1148549,
            'num' => '59',
        ),
        array('country' => 1,
            'title' => 'Приморский край',
            'vkid' => 1152714,
            'num' => '25',
        ),
        array('country' => 1,
            'title' => 'Псковская область',
            'vkid' => 1069004,
            'num' => '60',
        ),
        array('country' => 1,
            'title' => 'Ростовская область',
            'vkid' => 1077676,
            'num' => '61',
        ),
        array('country' => 1,
            'title' => 'Рязанская область',
            'vkid' => 1080077,
            'num' => '62',
        ),
        array('country' => 1,
            'title' => 'Самарская область',
            'vkid' => 1082931,
            'num' => '63',
        ),
        array('country' => 1,
            'title' => 'Саратовская область',
            'vkid' => 1084332,
            'num' => '64',
        ),
        array('country' => 1,
            'title' => 'Саха /Якутия/',
            'vkid' => 1153366,
            'num' => '14',
        ),
        array('country' => 1,
            'title' => 'Сахалинская область',
            'vkid' => 1153840,
            'num' => '65',
        ),
        array('country' => 1,
            'title' => 'Свердловская область',
            'vkid' => 1154131,
            'num' => '66',
        ),
        array('country' => 1,
            'title' => 'Северная Осетия - Алания',
            'vkid' => 1086244,
            'num' => '15',
        ),
        array('country' => 1,
            'title' => 'Смоленская область',
            'vkid' => 1086468,
            'num' => '67',
        ),
        array('country' => 1,
            'title' => 'Ставропольский край',
            'vkid' => 1091406,
            'num' => '26',
        ),
        array('country' => 1,
            'title' => 'Таймырский (Долгано-Ненецкий) АО',
            'vkid' => 1156333,
            'num' => '24',
        ),
        array('country' => 1,
            'title' => 'Тамбовская область',
            'vkid' => 1092174,
            'num' => '68',
        ),
        array('country' => 1,
            'title' => 'Татарстан',
            'vkid' => 1094197,
            'num' => '16',
        ),
        array('country' => 1,
            'title' => 'Тверская область',
            'vkid' => 1097508,
            'num' => '69',
        ),
        array('country' => 1,
            'title' => 'Томская область',
            'vkid' => 1156388,
            'num' => '70',
        ),
        array('country' => 1,
            'title' => 'Тульская область',
            'vkid' => 1105465,
            'num' => '71',
        ),
        array('country' => 1,
            'title' => 'Тыва',
            'vkid' => 1157049,
            'num' => '17',
        ),
        array('country' => 1,
            'title' => 'Тюменская область',
            'vkid' => 1157218,
            'num' => '72',
        ),
        array('country' => 1,
            'title' => 'Удмуртская',
            'vkid' => 1109098,
            'num' => '18',
        ),
        array('country' => 1,
            'title' => 'Ульяновская область',
            'vkid' => 1111137,
            'num' => '73',
        ),
        array('country' => 1,
            'title' => 'Хабаровский край',
            'vkid' => 1158917,
            'num' => '27',
        ),
        array('country' => 1,
            'title' => 'Хакасия',
            'vkid' => 1159424,
            'num' => '19',
        ),
        array('country' => 1,
            'title' => 'Ханты-Мансийский Автономный округ - Югра АО',
            'vkid' => 1159710,
            'num' => '86',
        ),
        array('country' => 1,
            'title' => 'Челябинская область',
            'vkid' => 1112201,
            'num' => '74',
        ),
        array('country' => 1,
            'title' => 'Чеченская',
            'vkid' => 1113642,
            'num' => '20',
        ),
        array('country' => 1,
            'title' => 'Чувашская',
            'vkid' => 1113937,
            'num' => '21',
        ),
        array('country' => 1,
            'title' => 'Чукотский АО',
            'vkid' => 1160844,
            'num' => '87',
        ),
        array('country' => 1,
            'title' => 'Ямало-Ненецкий  АО',
            'vkid' => 1160930,
            'num' => '89',
        ),
        array('country' => 1,
            'title' => 'Ярославская область',
            'vkid' => 1115658,
            'num' => '76',
        ),


/*
        array(
            'country' => 2,
            'title' => 'Винницкая область',
            'vkid' => 1500595,
            'num' => '02',
        ),
        array(
            'country' => 2,
            'title' => 'Волынская область',
            'vkid' => 1501549,
            'num' => '03',
        ),
        array(
            'country' => 2,
            'title' => 'Днепропетровская область',
            'vkid' => 1502117,
            'num' => '04',
        ),
        array(
            'country' => 2,
            'title' => 'Донецкая область',
            'vkid' => 1502709,
            'num' => '05',
        ),
        array(
            'country' => 2,
            'title' => 'Житомирская область',
            'vkid' => 1503296,
            'num' => '06',
        ),
        array(
            'country' => 2,
            'title' => 'Закарпатская область',
            'vkid' => 1504102,
            'num' => '07',
        ),
        array(
            'country' => 2,
            'title' => 'Запорожская область',
            'vkid' => 1504503,
            'num' => '08',
        ),
        array(
            'country' => 2,
            'title' => 'Ивано-Франковская область',
            'vkid' => 1504975,
            'num' => '09',
        ),
        array(
            'country' => 2,
            'title' => 'Киевская область',
            'vkid' => 1505578,
            'num' => '10',
        ),
        array(
            'country' => 2,
            'title' => 'Киев',
            'vkid' => 1505578,
            'num' => '11',
        ),
        array(
            'country' => 2,
            'title' => 'Кировоградская область',
            'vkid' => 1506310,
            'num' => '12',
        ),
        array(
            'country' => 2,
            'title' => 'Крым',
            'vkid' => 1500001,
            'num' => '01',
        ),
        array(
            'country' => 2,
            'title' => 'Луганская область',
            'vkid' => 1506831,
            'num' => '13',
        ),
        array(
            'country' => 2,
            'title' => 'Львовская область',
            'vkid' => 1507378,
            'num' => '14',
        ),
        array(
            'country' => 2,
            'title' => 'Николаевская область',
            'vkid' => 1508347,
            'num' => '15',
        ),
        array(
            'country' => 2,
            'title' => 'Одесская область',
            'vkid' => 1508808,
            'num' => '16',
        ),
        array(
            'country' => 2,
            'title' => 'Полтавская область',
            'vkid' => 1509477,
            'num' => '17',
        ),
        array(
            'country' => 2,
            'title' => 'Ровненская область',
            'vkid' => 1510213,
            'num' => '18',
        ),
        array(
            'country' => 2,
            'title' => 'Сумская область',
            'vkid' => 1510799,
            'num' => '19',
        ),
        array(
            'country' => 2,
            'title' => 'Тернопольская область',
            'vkid' => 1511345,
            'num' => '20',
        ),
        array(
            'country' => 2,
            'title' => 'Харьковская область',
            'vkid' => 1512004,
            'num' => '21',
        ),
        array(
            'country' => 2,
            'title' => 'Херсонская область',
            'vkid' => 1512710,
            'num' => '22',
        ),
        array(
            'country' => 2,
            'title' => 'Хмельницкая область',
            'vkid' => 1513133,
            'num' => '23',
        ),
        array(
            'country' => 2,
            'title' => 'Черкасская область',
            'vkid' => 1513930,
            'num' => '24',
        ),
        array(
            'country' => 2,
            'title' => 'Черниговская область',
            'vkid' => 1514896,
            'num' => '25',
        ),
        array(
            'country' => 2,
            'title' => 'Черновицкая область',
            'vkid' => 1514541,
            'num' => '26 ',
        ),


        array(
            'country' => 3,
            'title' => 'Брестская область',
            'vkid' => 1600001,
            'num' => 'BR',
        ),
        array(
            'country' => 3,
            'title' => 'Витебская область',
            'vkid' => 1600563,
            'num' => 'VI',
        ),
        array(
            'country' => 3,
            'title' => 'Гомельская область',
            'vkid' => 1601201,
            'num' => 'HO',
        ),
        array(
            'country' => 3,
            'title' => 'Гродненская область',
            'vkid' => 1601806,
            'num' => 'HR',
        ),
        array(
            'country' => 3,
            'title' => 'Минская область',
            'vkid' => 1602269,
            'num' => 'MI',
        ),
        array(
            'country' => 3,
            'title' => 'Могилевская область',
            'vkid' => 1602923,
            'num' => 'MA',
        ),*/
    ];

    private static $countryData = [
        array(
            'title' => 'Армения',
            'vkid' => 6,
            'num' => '80',
        ),
        array(
            'title' => 'Беларусь',
            'vkid' => 3,
            'num' => '81',
        ),
        array(
            'title' => 'Грузия',
            'vkid' => 7,
            'num' => '82',
        ),
        array(
            'title' => 'Кыргызстан',
            'vkid' => 11,
            'num' => '84',
        ),
        array(
            'title' => 'Молдова',
            'vkid' => 15,
            'num' => '85',
        ),
        array(
            'title' => 'Туркменистан',
            'vkid' => 17,
            'num' => '88',
        ),
        array(
            'title' => 'Украина',
            'vkid' => 2,
            'num' => '90',
        ),
        array(
            'title' => 'Казахстан',
            'vkid' => 4,
            'num' => '93',
        ),
        array(
            'title' => 'Литва',
            'vkid' => 13,
            'num' => '94',
        ),
        array(
            'title' => 'Латвия',
            'vkid' => 12,
            'num' => '95',
        ),
        array(
            'title' => 'Узбекистан',
            'vkid' => 18,
            'num' => '96',
        ),
        array(
            'title' => 'Азербайджан',
            'vkid' => 5,
            'num' => '97',
        ),
        array(
            'title' => 'Эстония',
            'vkid' => 14,
            'num' => '98',
        )
    ];

    public static function getRegionData($regionName, $countryName = null)
    {
        $regionName = preg_replace('@\s+@', ' ', trim(mb_strtolower($regionName)));
        $countryName = preg_replace('@\s+@', ' ', trim(mb_strtolower($countryName)));

        if ($regionName) foreach(self::$regionData as $item){
            if (mb_strpos($regionName, mb_strtolower($item['title']) )!==false){
                return $item;
            }
        }
        if ($countryName) foreach(self::$countryData as $item){
            if (mb_strpos($countryName, mb_strtolower($item['title']) )!==false){
                return $item;
            }
        }
        return false;
    }

    public static function getByCode($regionCode)
    {
        foreach(array_merge(self::$regionData, self::$countryData) as $item){
            if ($regionCode == $item['num']){
                return $item;
            }
        }
        return false;
    }
}